#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 30 15:32:36 2018

@author: mythri
"""

# SDG keywords used to extract summary
summary_keywords = {
        "SDG1": "end poverty access basic services extreme poverty pro-poor international poverty line social protection system resilience poor national poverty line investment in poverty poverty investment poverty eradication gender-sensitive poverty reduction mobilization development cooperation rights ownership l property climate-related extreme events shocks disasters exposure vulnerability",
        "SDG2": "hunger sufficient food insecurity starve starvation agriculture malnutrition stunting wasting nutrition undernourishment fies children nutritional needs lactating women child growth stards agricultural productivity food producers small-scale access to l sustainable food production resilient agricultural practices sustainable agriculture genetic diversity genetic resources local breeds agriculture orientation index agricultural productive capacity rural infrastructure agricultural research producer support estimate agricultural export subsidies doha development round trade restrictions food price food prices food commodity markets",
        "SDG3": "mental health wellbeing well-being well being disease tropical diseases vaccines vaccination medicines medical maternal mortality ratio heath-care healthcare illness illnesses 100,000 live births under-five mortality rate neonatal preventable deaths epidemics aids hiv tuberculosis malaria hepatitis b non-communicable diseases suicide mortality premature mortality substance abuse narcotic drug abuse alcohol treatment interventions road traffic health-care services healthcare services health care services family planning reproductive health adolescent birth rate health coverage financial risk protection tracer interventions health insurance health services child health vaccines for all hazardous chemicals air pollution contamination water sanitation hygiene wash services poisoning world health organization framework convention tobacco medical research health facilities public health health worker health financing health workforce international health regulations ihr health emergency preparedness health risks",
        "SDG4": "education school schools vocational training free education equitable education quality education primary education secondary education learning outcome priciency level young people early childhood development pre-primary education organized learning primary education technical education vocational education tertiary education university skills for employment information communications technology skills ict skills vocational skills gender disparities vocational training parity indices literacy numeracy global citizenship education education for sustainable development sustainable development education national education policies curricula teacher education student assessment education facilities schools with access to pedagogical purposes students with disabilities scholarship scholarships higher education target 4.10 teachers teacher training pedagogical training ",
        "SDG5": "gender women fgm rape equality equalities sexual equal rights female marriage discrimination violence trafficking sexual exploitation marriage female genital harmful practices married unpaid care domestic work shared responsibility within household unpaid domestic care work equal opportunities for leadership parliaments parliament local government managerial positions sexual health reproductive health reproductive rights programme action international conference on population development beijing platform for action decisions regarding sexual relations contraceptive use sexual relations rights l enabling technology phone public allocations gender equality empowerment ",
        "SDG6": "water sanitation wastewater water-use water-related drinking water sanitation hygiene open defecation h-washing soap water quality pollution dumping release hazardous wastewater recycling reuse freshwater water scarcity water-use efficiency water use efficiency water stress water resources management transboundary water cooperation water-related ecosystems water related ecosystems international cooperation water harvesting desalination water efficiency wastewater treatment technologies local communities sanitation management",
        "SDG7": "energy solar fuel electricity energy services electricity clean fuels clean technology affordable renewable energy energy consumption energy efficiency energy intensity primary energy international cooperation clean energy research technology infrastructure energy services investment energy efficiency sustainable energy",
        "SDG8": "jobs labor labour employment work economic growth economic growth growth rate gdp per capita product growth economic productivity economic diversification technological upgrading innovation growth rate gdp per employed development-oriented policies productive activities job creation entrepreneurship innovation informal employment global resource efficiency material footprint productive employment full employment decent work equal pay hourly earning unemployment rate youth forced labour forced labor modern slavery human trafficking child labour rights labor rights working environment migrant workers precarious employment occupational injuries freedom association collective bargaining local culture local products tourism domestic financial institutions banking services insurance services financial services commercial bank branches atms aid for trade least developed countries youth employment global jobs pact international labour organization international labor organization employment programmes employment programs",
        "SDG9": "infrastructure industry industries innovation manufacturing industrialization infrastructure equitable access all-season road all season road freight volume passenger volume economic development sustainable industrialization share employment gross domestic product manufacturing small-scale small scale resource-use efficiency resource use efficiency industrial process co2 emissions research development scientific research innovation public research private research technological capabilities infrastructure development support to infrastructure domestic industrial diversification high-tech industry high tech industry technology development information communications technology ict internet mobile network",
        "SDG10": "inequality inequalities income migration income growth household expenditure income per capita inclusion all political inclusion equal opportunity inequalities discriminatory social protection fiscal wage labour share labor share global financial market financial institution financial soundness indicators economic institutions international financial institutions voting rights migration mobility people migration policies recruitment cost differential treatment tariff foreign direct investment financial flow migrant remittance remittance corridor remittance cost",
        "SDG11": "city cities urban heritage slums public transport public transportation local materials urbanization housing slums urban population informal settlement inadequate housing affordable housing transport system road safety public transport sustainable transport urbanization human settlement l consumption rate population growth rate civil society urban planning urban management direct participation heritage disaster environmental impact air quality waste management urban solid waste fine particulate matter PM2.5 PM 2.5 PM10 PM 10 built-up area open space public space green space harassment safe space inclusive space economic link social link environmental link per-urban rural area development plan development planning development plans human settlement inclusion resource efficiency resilience to disaster sendai framework disaster risk reduction disaster risk management sustainable building resilient building resource-efficient building",
        "SDG12": "consumption production fossil fuel fossil-fuel sustainable consumption sustainable production 10 year framework sustainable consumption production scp sustainable management material footprint efficient use global food waste food loss post-harvest loss environmental agreement environmental agreements hazardous waste waste generation recycling recycle companies sustainability report sustainable practice public procurement nature awareness for sustainable development climate change education sustainable pattern scientific capacity technological capacity environmentally sound technologies sustainable development impacts sustainable tourism monitoring tools evaluation tools fossil-fuel wasteful consumption market distortion taxation harmful subsidies",
        "SDG13": "climate global warming globalwarming early warningnatural disasters hazards adaptive capacity climate change measures climate resilience greenhouse gas emissions climate change mitigation climate change adaptation climate change impact reduction climate change early warning technology transfer united nations framework convention on climate change green climate fund transparency climate change planning climate change management",
        "SDG14": "ocean oceans sea seas river rivers fish overfishing fishing marine coastal coast marine pollution debris nutrient pollution coastal eutrophication marine ecosystems coastal ecosystems healthy oceans productive oceans national exclusive economic zones ocean acidification marine acidity regulate harvesting overfishing fishing fish stock conserve coastal areas marine areas protected areas fisheries subsidies marine resources aquaculture tourism sustainable fisheries marine technology intergovernmental oceanographic commission criteria guidelines ocean health marine biodiversity fisher marine market small-scale small scale fishery fisheries unclos use ocean use ocean future we want ocean resources",
        "SDG15": "deforest deforestation desertification animals plants terrestrial forest wildlife species reforestation biodiversity freshwater forest wetl mountain dryl deforestation restore degraded forest afforestation reforestation sustainable forest management desertification drought flood degradation neutral degraded l mountain natural habitat loss biodiversity biodiversity loss extinction threatened species red list index genetic resources poaching protected species flora fauna wildlife invasive alien species priority species ecosystem values biodiversity values aichi biodiversity targets strategic plan for biodiversity aichi biodiversity target use biodiversity biodiversity uses use ecosystem ecosystems uses sustainable forest management sustainable livelihood opportunities poaching trafficking",
        "SDG16": "institutions peace justice bribe crime bribery reduce violence conflict deaths abuse exploitation trafficking children psychological physical punishment equal access justice rule law victimization unsentenced illicit financial flows arms flows stolen assets organized crimes organized crime corruption bribery business effective accountable institutions transparent institutions decision making global governance developing countries legal identity birth registration access to information fundamental freedoms violence terrorism crime crimes non-discriminatory laws non-discriminatory policies ",
        "SDG17": "partnership finance partnerships policy coherence technology innovation public-private resource mobilization domestic capacity tax revenue collection development assistance commitments oda oecd financial resources debt sustainability debt financing debt relief debt restructuring reduce debt debt distress promotion science technology innovation knowledge sharing technology cooperation agreements environmentally sound technologies technology bank innovation capacity capacity building national plans multilateral trading system doha development agenda exports duty free quota free market access macroeconomic stability policy coordination policy coherence policy coherence multi-stakeholder partnerships global partnerships multi-stakeholder partnerships data monitoring accountability capacity building small isl developing states disaggregated reliable data disaggregation existing initiatives gross domestic product statistical capacity building birth registration death registration"
        }


sdgs = {
        "SDG1": ["sdg 1 ", "sdg1 ", "goal 1 ", "poverty", "poor", "access basic services",
                 "pro poor"],
        "SDG2": ["sdg2 ", "sdg 2 ", "goal 2 ", "hunger", "food", "starve", "starvation",
                 "agriculture", "malnutrition", "stunting", "agricultural", "wasting", "nutrition", "nutritional",
                 "undernourishment"],
        "SDG3": ["sdg3", "sdg 3", "goal 3", "health", "wellbeing", "well being",
                 "disease", "diseases", "vaccines", "vaccination", "medicines", "medical", "mortality", "heath care",
                 "healthcare", "epidemics", "illness", "illnesses"],
        "SDG4": ["sdg4", "sdg 4", "goal 4", "education", "school", "schools",
                 "vocational training"],
        "SDG5": ["sdg5", "sdg 5", "goal 5", "gender", "women", "fgm", "rape", "equality", "equalities",
                 "sexual", "equal rights", "female", "marriage"],
        "SDG6": ["sdg6", "sdg 6", "goal 6", "water", "sanitation", "wastewater", "water use",
                 "water related"],
        "SDG7": ["sdg7", "sdg 7", "goal 7", "energy", "solar", "fuel", "electricity"],
        "SDG8": ["sdg8", "sdg 8", "goal 8", "jobs", "labor", "labour", "employment",
                 "economic growth"],
        "SDG9": ["sdg9", "sdg 9", "goal 9", "infrastructure", "industry", "industries",
                 "innovation", "manufacturing", "industrialization"],
        "SDG10": ["sdg10", "sdg 10", "goal 10", "inequality", "inequalities", "income",
                  "migration"],
        "SDG11": ["sdg11", "sdg 11", "goal 11", " city", "cities", "urban", "heritage", "slums",
                  "public transport", "public transportation", "local materials", "urbanization"],
        "SDG12": ["sdg12", "sdg 12", "goal 12", "consumption", "production", "fossil fuel"],
        "SDG13": ["sdg13", "sdg 13", "goal 13", "climate", "global warming", "globalwarming",
                  "early warning"],
        "SDG14": ["sdg14", "sdg 14", "goal 14", "ocean", "oceans", "sea", "seas", "river",
                  "rivers", "fish", "overfishing", "fishing", "marine", "coastal", "coast"],
        "SDG15": ["sdg15", "sdg 15", "goal 15", "deforest", "deforestation", "desertification",
                  "animals", "plants", "terrestrial", "forest", "wildlife", "species", "reforestation", "biodiversity"],
        "SDG16": ["sdg16", "sdg 16", "goal 16", "institutions", "peace", "justice", "bribe",
                  "crime", "bribery"],
        "SDG17": ["sdg17", "sdg 17", "goal 17", "partnership", "finance", "partnerships",
                  "policy coherence", "technology innovation", "public private"]
        }

stemmed_sdgs = {
          "SDG4": ["sdg4", "sdg 4", "goal 4", u"educ", "school", u"school", u"vocat train"],
          "SDG5": ["sdg5", "sdg 5", "goal 5", "gender", "women", "fgm", "rape", u"equal", u"equal", "sexual", u"equal right", u"femal", u"marriag"],
          "SDG6": ["sdg6", "sdg 6", "goal 6", "water", u"sanit", u"wastewat", "water use", u"water relat"],
          "SDG7": ["sdg7", "sdg 7", "goal 7", u"energi", "solar", "fuel", u"electr"],
          "SDG1": ["sdg 1", "sdg1", "goal 1", u"poverti", "poor", u"access basic servic", "pro poor"],
          "SDG2": ["sdg2", "sdg 2", "goal 2", "hunger", "food", u"starv", u"starvat", u"agricultur", u"malnutrit", u"stunt", u"agricultur", u"nutrit", u"nutrit", u"undernourish"],
          "SDG3": ["sdg3", "sdg 3", "goal 3", "health", u"wellb", u"well be", u"diseas", u"diseas", u"vaccin", u"vaccin", u"medicin", u"medic", u"mortal", "heath care", u"healthcar", u"epidem", u"ill", u"ill"],
          "SDG8": ["sdg8", "sdg 8", "goal 8", u"job", "labor", "labour", u"employ", u"econom growth"],
          "SDG9": ["sdg9", "sdg 9", "goal 9", u"infrastructur", u"industri", u"industri", u"innov", u"manufactur", u"industri"],
          "SDG16": ["sdg16", "sdg 16", "goal 16", u"institut", u"peac", u"justic", "bribe", "crime", u"briberi"],
          "SDG17": ["sdg17", "sdg 17", "goal 17", "partnership", u"financ", u"partnership", u"polici coher", u"technolog innov", u"public privat"],
          "SDG14": ["sdg14", "sdg 14", "goal 14", "ocean", u"ocean", "sea", u"sea", "river", u"river", "fish", u"overfish", u"fish", u"marin", "coastal", "coast"],
          "SDG15": ["sdg15", "sdg 15", "goal 15", "deforest", u"deforest", u"desertif", u"anim", u"plant", u"terrestri", "forest", u"wildlif", u"speci", u"reforest", u"biodivers"],
          "SDG12": ["sdg12", "sdg 12", "goal 12", u"consumpt", u"product", "fossil fuel"],
          "SDG13": ["sdg13", "sdg 13", "goal 13", u"climat", u"global warm", u"globalwarm", u"earli warn"],
          "SDG10": ["sdg10", "sdg 10", "goal 10", u"inequ", u"inequ", u"incom", u"migrat"],
          "SDG11": ["sdg11", "sdg 11", "goal 11", u"citi", u"citi", "urban", u"heritag", u"slum", "public transport", u"public transport", u"local materi", u"urban"]
        }


targets = {
            'SDG1' : {
                      "SDG1.1": ["target 1.1", "extreme poverty", "less $1.25", "international poverty"],
                       "SDG1.2": ["target 1.2", "national poverty"],
                       "SDG1.3": ["target 1.3", "social protection"],
                       "SDG1.4": ["target 1.4", "rights", "ownership", "land", "property"],
                       "SDG1.5": ["target 1.5", "resilience   poor", "climate extreme",
                                  "shocks disasters", "exposure", "vulnerability"],
                       "SDG1.A": ["target 1.A", "target 1.6", "mobilization", "development cooperation",
                                  "poverty reduction", "end poverty"],
                       "SDG1.B": ["target 1.B", "target 1.7", "pro poor", "gender sensitive",
                                  "investment poverty", "poverty investment", "poverty eradication"]
                       },
            'SDG2' : {

                    "SDG2.1": ["target 2.1", "hunger", "sufficient food", "undernourishment", "food insecurity", "fies"],
                   "SDG2.2": ["target 2.2", "malnutrition", "stunting", "wasting children", "nutritional needs",
                              "lactating", "child growth standards"],
                   "SDG2.3": ["target 2.3", "agricultural productivity", "food producers", "small scale", "access land"],
                   "SDG2.4": ["target 2.4", "sustainable food production", "resilient agricultural practices",
                              "sustainable agriculture"],
                   "SDG2.5": ["target 2.5", "genetic diversity", "genetic resources", "local breeds"],
                   "SDG2.A": ["target 2.a", "target 2.6", "agriculture orientation index", "agricultural productive capacity",
                              "rural infrastructure", "agricultural research"],
                   "SDG2.B": ["target 2.b", "target 2.7", "producer support estimate", "agricultural export subsidies",
                              "doha development round", "trade restrictions"],
                   "SDG2.C": ["target 2.c", "target 2.8", "food price", "food prices", "food commodity markets"]
                   },
            'SDG3' :{
                      "SDG3.1": ["target 3.1", "maternal mortality ratio", "100,000 live births"],
                       "SDG3.2": ["target 3.2", "five mortality rate", "neonatal mortality rate", "preventable deaths",
                                  "1,000 live births"],
                       "SDG3.3": ["target 3.3", "epidemics", "aids", "hiv", "tuberculosis", "malaria", "hepatitis b",
                                  "tropical diseases"],
                       "SDG3.4": ["target 3.4", "non communicable diseases", "suicide mortality", "mental health",
                                  "premature mortality"],
                       "SDG3.5": ["target 3.5", "substance abuse", "narcotic drug abuse", "alcohol", "treatment interventions"],
                       "SDG3.6": ["target 3.6", "road traffic"],
                       "SDG3.7": ["target 3.7", "health care services", "healthcare services", "health care services",
                                  "family planning", "reproductive health", "adolescent birth rate"],
                       "SDG3.8": ["target 3.8", "health coverage", "financial risk protection", "tracer interventions",
                                  "health insurance", "health services", "child health", "vaccines", "vaccine"],
                       "SDG3.9": ["target 3.9", "hazardous chemicals", "air pollution", "contamination", "water", "sanitation",
                                  "hygiene", "wash services", "poisoning"],
                       "SDG3.A": ["target 3.a", "target 3.10", "world health organization framework convention", "tobacco"],
                       "SDG3.B": ["target 3.b", "target 3.11", "medical research", "health facilities", "public health"],
                       "SDG3.C": ["target 3.c", "target 3.12", "health worker", "health financing", "health workforce"],
                       "SDG3.D": ["target 3.d", "target 3.13", "international health regulations", "ihr",
                                  "health emergency preparedness", "health risks"],
                    },
            'SDG4' : {
                       "SDG4.1": ["target 4.1", "free education", "equitable education", "quality education", "primary education",
                                  "secondary education", "learning outcome", "proficiency level", "young people"],
                       "SDG4.2": ["target 4.2", "early childhood development", "pre primary education", "organized learning",
                                  "primary education"],
                       "SDG4.3": ["target 4.3", "technical education", "vocational education", "tertiary education", "university"],
                       "SDG4.4": ["target 4.4", "skills employment", "information   communications technology skills",
                                  "ict skills", "vocational skills"],
                       "SDG4.5": ["target 4.5", "gender disparities", "vocational training", "parity indices"],
                        "SDG4.6": ["target 4.6", "literacy", "numeracy"],
                        "SDG4.7": ["target 4.7", "global citizenship", "education sustainable development",
                                   "sustainable development education", "national education policies", "curricula",
                                   "teacher education", "student assessment"],
                       "SDG4.A": ["target 4.a", "target 4.8", "education facilities", "schools access ",
                                  "pedagogical purposes", "students disabilities"],
                       "SDG4.B": ["target 4.b", "target 4.9", "scholarship", "scholarships", "higher education"],
                       "SDG4.C": ["target 4.c", "target 4.10", "teachers", "teacher training", "pedagogical training"]
                       },
            'SDG5' : {
                       "SDG5.1": ["target 5.1", "discrimination"],
                       "SDG5.2": ["target 5.2", "violence", "trafficking", "sexual exploitation"],
                       "SDG5.3": ["target 5.3", "marriage", "female genital", "harmful practices", "married"],
                       "SDG5.4": ["target 5.4", "unpaid care", "domestic work", "shared responsibility within household",
                                  "unpaid domestic", "care work"],
                       "SDG5.5": ["target 5.5", "equal opportunities leadership", "parliaments", "parliament","local government",
                                  "managerial positions"],
                       "SDG5.6": ["target 5.6", "sexual health", "reproductive health", "reproductive rights",
                                  "programme   action   international conference   population   development",
                                  "beijing platform action", "decisions regarding sexual relations", "contraceptive use",
                                  "sexual relations"],
                       "SDG5.A": ["target 5.a", "target 5.7", "rights", "land"],
                       "SDG5.B": ["target 5.b", "target 5.8", "enabling technology", "phone"],
                       "SDG5.C": ["target 5.c", "target 5.9", "public allocations", "gender equality", "empowerment"]
                       },
            'SDG6' : {
                           "SDG6.1": ["target 6.1", "drinking water"],
                           "SDG6.2": ["target 6.2", "sanitation", "hygiene", "open defecation", "hand washing", "soap"],
                           "SDG6.3": ["target 6.3", "water quality", "pollution", "dumping", "release   hazardous",
                                      "wastewater", "recycling", "reuse"],
                           "SDG6.4": ["target 6.4", "freshwater", "water scarcity", "water use efficiency", "water stress"],
                           "SDG6.5": ["target 6.5", "water resources management", "transboundary", "water cooperation"],
                           "SDG6.6": ["target 6.6", "water related ecosystems"],
                           "SDG6.A": ["target 6.a", "target 6.7", "international cooperation", "water harvesting", "desalination",
                                      "water efficiency", "wastewater treatment", "technologies"],
                           "SDG6.B": ["target 6.B", "target 6.8", "local communities", "sanitation management"],
                    },
            'SDG7' : {
                     "SDG7.1": ["target 7.1", "energy services", "electricity", "clean fuels", "clean technology", "affordable"],
                       "SDG7.2": ["target 7.2", "renewable energy", "energy consumption"],
                       "SDG7.3": ["target 7.3", "energy efficiency", "energy intensity", "primary energy"],
                       "SDG7.A": ["target 7.A", "target 7.4", "international cooperation", "clean energy research", "technology",
                                  "infrastructure"],
                       "SDG7.B": ["target 7.B", "target 7.5", "energy services", "investment", "energy efficiency",
                                  "sustainable energy"],
                    },
          'SDG8' : {
                       "SDG8.1": ["target 8.1", "economic growth", "growth rate   gdp per capita", "product growth"],
                       "SDG8.2": ["target 8.2", "economic productivity", "economic diversification",
                                  "technological upgrading", "innovation", "growth rate   gdp per employed"],
                       "SDG8.3": ["target 8.3", "development oriented policies", "productive activities", "job creation",
                                  "entrepreneurship", "innovation", "informal employment"],
                       "SDG8.4": ["target 8.4", "global resource efficiency", "material footprint"],
                       "SDG8.5": ["target 8.5", "productive employment", "full employment", "decent work", "equal pay",
                                  "hourly earning", "unemployment rate"],
                       "SDG8.6": ["target 8.6", "youth"],
                       "SDG8.7": ["target 8.7", "forced labour", "forced labor", "modern slavery", "human trafficking", "child"],
                       "SDG8.8": ["target 8.8", "labour rights", "labor rights", "working environment", "migrant workers",
                                  "precarious employment", "occupational injuries",
                                  "freedom   association   collective bargaining"],
                       "SDG8.9": ["target 8.9", "local culture", "local products", "tourism"],
                       "SDG8.10": ["target 8.10", "domestic financial institutions", "banking services", "insurance services",
                                   "financial services", "commercial bank branches", "atms"],
                       "SDG8.A": ["target 8.A", "target 8.11", "aid trade", "least developed countries"],
                       "SDG8.B": ["target 8.B", "target 8.12", "youth employment",
                                  "global jobs pact   international labour organization", "international labor organization",
                                  "employment programmes", "employment programs"]
                       },
          'SDG9' : {
                       "SDG9.1": ["target 9.1", "infrastructure", "equitable access", "season road",
                                  "freight volume", "passenger volume", "economic development"],
                       "SDG9.2": ["target 9.2", "sustainable industrialization", "share   employment", "gross domestic product",
                                  "manufacturing"],
                       "SDG9.3": ["target 9.3", "small scale"],
                       "SDG9.4": ["target 9.4", "resource use efficiency", "industrial process",
                                  "co2 emissions"],
                       "SDG9.5": ["target 9.5", "research   development", "scientific research", "innovation", "public research",
                                  "private research", "technological capabilities"],
                       "SDG9.A": ["target 9.A", "target 9.6", "infrastructure development", "support infrastructure"],
                       "SDG9.B": ["target 9.B", "target 9.7", "domestic", "industrial diversification",
                                  "high tech industry", "technology development"],
                       "SDG9.C": ["target 9.C", "target 9.8", "information   communications technology", "ict", "internet",
                                  "mobile network"]
                       },
          'SDG10' : {
                       "SDG10.1": ["target 10.1", "income growth", "household expenditure", "income per capita"],
                       "SDG10.2": ["target 10.2", "inclusion  ", "political inclusion"],
                       "SDG10.3": ["target 10.3", "equal opportunity", "inequalities", "discriminatory"],
                       "SDG10.4": ["target 10.4", "social protection", "fiscal", "wage", "labour share", "labor share"],
                       "SDG10.5": ["target 10.5", "global financial market", "financial institution",
                                   "financial soundness indicators"],
                       "SDG10.6": ["target 10.6", "economic institutions", "international financial institutions", "voting rights"],
                       "SDG10.7": ["target 10.7", "migration", "mobility   people", "migration policies", "recruitment cost"],
                       "SDG10.A": ["target 10.A", "differential treatment", "tariff"],
                       "SDG10.B": ["target 10.B", "foreign direct investment", "financial flow"],
                       "SDG10.C": ["target 10.C", "migrant remittance", "remittance corridor", "remittance cost"]
                       },
          'SDG11' : {
                       "SDG11.1": ["target 11.1", "housing", "slums", "urban population", "informal settlement",
                                   "inadequate housing", "affordable housing"],
                       "SDG11.2": ["target 11.2", "transport system", "road safety", "public transport", "sustainable transport"],
                       "SDG11.3": ["target 11.3", "urbanization", "human settlement", "land consumption rate",
                                   "population growth rate", "civil society", "urban planning", "urban management",
                                   "direct participation"],
                       "SDG11.4": ["target 11.4", "heritage"],
                       "SDG11.5": ["target 11.5", "disaster"],
                       "SDG11.6": ["target 11.6", "environmental impact", "air quality", "waste management", "urban solid waste",
                                   "fine particulate matter", "PM2.5", "PM 2.5", "PM10", "PM 10"],
                       "SDG11.7": ["target 11.7", "built up area", "open space", "public space", "green space", "harassment",
                                   "safe space", "inclusive space"],
                       "SDG11.A": ["target 11.A", "economic link", "social link", "environmental link", "per urban", "rural area",
                                   "development plan", "development planning", "development plans"],
                       "SDG11.B": ["target 11.B", "human settlement", "inclusion", "resource efficiency", "resilience disaster",
                                   "sendai framework", "disaster risk reduction", "disaster risk management"],
                       "SDG11.C": ["target 11.C", "sustainable building", "resilient building", "resource efficient building"]
                       },
          'SDG12' : {
                       "SDG12.1": ["target 12.1", "sustainable consumption", "sustainable production", "10 year framework",
                                   "sustainable consumption   production", "scp"],
                       "SDG12.2": ["target 12.2", "sustainable management", "material footprint", "efficient use"],
                       "SDG12.3": ["target 12.3", "global food waste", "food loss", "post harvest loss"],
                       "SDG12.4": ["target 12.4", "environmental agreement", "environmental agreements", "hazardous waste"],
                       "SDG12.5": ["target 12.5", "waste generation", "recycling", "recycle"],
                       "SDG12.6": ["target 12.6", "companies", "sustainability report", "sustainable practice"],
                       "SDG12.7": ["target 12.7", "public procurement"],
                       "SDG12.8": ["target 12.8", "nature", "awareness sustainable development", "climate change education"],
                       "SDG12.A": ["target 12.a", "target 12.9", "sustainable pattern", "scientific capacity",
                                   "technological capacity", "environmentally sound technologies"],
                       "SDG12.B": ["target 12.b", "target 12.10", "sustainable development impacts", "sustainable tourism",
                                   "monitoring tools", "evaluation tools"],
                       "SDG12.C": ["target 12.c", "target 12.11", "fossil fuel", "wasteful consumption", "market distortion",
                                   "taxation", "harmful subsidies"]
                  },
          'SDG13': {
                       "SDG13.1": ["target 13.1", "natural disasters", "hazards", "adaptive capacity"],
                       "SDG13.2": ["target 13.2", "climate change measures", "climate resilience", "greenhouse gas emissions"],
                       "SDG13.3": ["target 13.3", "climate change mitigation", "climate change adaptation",
                                   "climate change impact reduction", "climate change early warning", "technology transfer"],
                       "SDG13.A": ["target 13.4", "target 13.a", "united nations framework convention   climate change",
                                   "green climate fund", "transparency"],
                       "SDG13.B": ["target 13.5", "target 13.b", "climate change planning", "climate change management"]
                       },
          'SDG14' : {
                       "SDG14.1": ["target 14.1", "marine pollution", "debris", "nutrient pollution",
                                   "coastal eutrophication"],
                       "SDG14.2": ["target 14.2", "marine ecosystems", "coastal ecosystems", "healthy oceans", "productive oceans",
                                   "national exclusive economic zones"],
                       "SDG14.3": ["target 14.3", "ocean acidification", "marine acidity"],
                       "SDG14.4": ["target 14.4", "regulate harvesting", "overfishing", "fishing", "fish stock"],
                       "SDG14.5": ["target 14.5", "conserve", "coastal areas", "marine areas", "protected areas"],
                       "SDG14.6": ["target 14.6", "fisheries subsidies"],
                       "SDG14.7": ["target 14.7", "marine resources", "aquaculture", "tourism", "sustainable fisheries"],
                       "SDG14.A": ["target 14.a", "target 14.8", "marine technology",
                                   "intergovernmental oceanographic commission criteria   guidelines",
                                   "ocean health", "marine biodiversity"],
                       "SDG14.B": ["target 14.b", "target 14.9", "fisher", "marine market", "small scale", "fishery",
                                   "fisheries"],
                       "SDG14.C": ["target 14.c", "target 14.10", "unclos", "use   ocean", "use   ocean",
                                   " future we want", "ocean resources"]
                       },
          'SDG15' : {
                       "SDG15.1": ["target 15.1", "freshwater", "forest", "wetland", "mountain", "dryland"],
                       "SDG15.2": ["target 15.2", "deforestation", "restore degraded forest", "afforestation", "reforestation",
                                   "sustainable forest management"],
                       "SDG15.3": ["target 15.3", "desertification", "drought", "flood", "degradation neutral", "degraded land"],
                       "SDG15.4": ["target 15.4", "mountain"],
                       "SDG15.5": ["target 15.5", "natural habitat", "loss   biodiversity", "biodiversity loss", "extinction",
                                   "threatened species", "red list index"],
                       "SDG15.6": ["target 15.6", "genetic resources"],
                       "SDG15.7": ["target 15.7", "poaching", "protected species", "flora", "fauna", "wildlife"],
                       "SDG15.8": ["target 15.8", "invasive alien species", "priority species"],
                       "SDG15.9": ["target 15.9", "ecosystem values", "biodiversity values", "aichi biodiversity targets",
                                   "strategic plan biodiversity", "aichi biodiversity target"],
                       "SDG15.A": ["target 15.a", "target 15.10", "use   biodiversity", "biodiversity uses", "use   ecosystem",
                                   "ecosystems uses"],
                       "SDG15.B": ["target 15.b", "target 15.11", "sustainable forest management"],
                       "SDG15.C": ["target 15.c", "target 15.12", "sustainable livelihood opportunities",
                                   "poaching", "trafficking"]
                       },
          'SDG16' : {
                       "SDG16.1": ["target 16.1", "reduce violence", "conflict", "deaths"],
                       "SDG16.2": ["target 16.2", "abuse", "exploitation", "trafficking", "children", "psychological",
                                   "physical punishment"],
                       "SDG16.3": ["target 16.3", "equal access justice", "rule   law", "victimization", "unsentenced"],
                       "SDG16.4": ["target 16.4", "illicit financial flows", "arms flows", "stolen assets", "organized crimes",
                                   "organized crime"],
                       "SDG16.5": ["target 16.5", "corruption", "bribery", "business"],
                       "SDG16.6": ["target 16.6", "effective", "accountable institutions", "transparent institutions"],
                       "SDG16.7": ["target 16.7", "decision making"],
                       "SDG16.8": ["target 16.8", "global governance", "developing countries"],
                       "SDG16.9": ["target 16.9", "legal identity", "birth registration"],
                       "SDG16.10": ["target 16.10", "access information", "fundamental freedoms"],
                       "SDG16.A": ["target 16.a", "target 16.11", "violence", "terrorism" "crime", "crimes"],
                       "SDG16.B": ["target 16.b", "target 16.12", "non discriminatory laws", "non discriminatory policies"]
                       },
          'SDG17': {
                       "SDG17.1": ["target 17.1", "resource mobilization", "domestic capacity", "tax", "revenue collection"],
                       "SDG17.2": ["target 17.2", "development assistance commitments", "oda", "oecd"],
                       "SDG17.3": ["target 17.3", "financial resources"],
                       "SDG17.4": ["target 17.4", "debt sustainability", "debt financing", "debt relief", "debt restructuring",
                                   "reduce debt", "debt distress"],
                       "SDG17.5": ["target 17.5", "promotion"],
                       "SDG17.6": ["target 17.6", "science", "technology", "innovation", "knowledge sharing",
                                   "technology cooperation agreements"],
                       "SDG17.7": ["target 17.7", "environmentally sound technologies"],
                       "SDG17.8": ["target 17.8", "technology bank", "innovation capacity"],
                       "SDG17.9": ["target 17.9", "capacity building", "national plans"],
                       "SDG17.10": ["target 17.10", "multilateral trading system", "doha development agenda"],
                       "SDG17.11": ["target 17.11", "exports"],
                       "SDG17.12": ["target 17.12", "duty free", "quota free", "market access"],
                       "SDG17.13": ["target 17.13", "macroeconomic stability", "policy coordination", "policy coherence"],
                       "SDG17.14": ["target 17.14", "policy coherence"],
                       "SDG17.15": ["target 17.15", "multi stakeholder partnerships"],
                       "SDG17.16": ["target 17.16", "global partnerships", "multi stakeholder partnerships"],
                       "SDG17.17": ["target 17.17", "data", "monitoring", "accountability"],
                       "SDG17.18": ["target 17.18", "capacity building", "small island developing states", "disaggregated",
                                    "reliable data", "disaggregation"],
                       "SDG17.19": ["target 17.19", "existing initiatives", "gross domestic product",
                                    "statistical capacity building", "birth registration", "death registration"]
                       }
          }


stemmed_targets = {

            'SDG1': {
                      'SDG1.A': ['target 1.a', 'target 1.6', u'mobil', u'develop cooper', u'poverti reduct', u'end poverti'],
                      'SDG1.B': ['target 1.b', 'target 1.7', 'pro poor', u'gender sensit', u'invest poverti', u'poverti invest', u'poverti erad'],
                      'SDG1.1': ['target 1.1', u'extrem poverti', u'less $ 1.25', u'intern poverti'],
                      'SDG1.3': ['target 1.3', u'social protect'],
                      'SDG1.2': ['target 1.2', u'nation poverti'],
                      'SDG1.5': ['target 1.5', u'resili poor', u'climat extrem', u'shock disast', u'exposur', u'vulner'],
                      'SDG1.4': ['target 1.4', u'right', 'ownership', 'land', u'properti']
                      },
            'SDG2': {
                    'SDG2.4': ['target 2.4', u'sustain food product', u'resili agricultur practic', u'sustain agricultur'],
                    'SDG2.5': ['target 2.5', u'genet divers', u'genet resourc', u'local breed'],
                    'SDG2.2': ['target 2.2', u'malnutrit', u'stunt', u'nutrit need', u'lactat', u'child growth standard'],
                    'SDG2.3': ['target 2.3', u'agricultur product', u'food produc', 'small scale', u'access land'],
                    'SDG2.1': ['target 2.1', 'hunger', u'suffici food', u'undernourish', u'food insecur', u'fie'],
                    'SDG2.B': ['target 2.b', 'target 2.7', u'produc support estim', u'agricultur export subsidi', u'doha develop round', u'trade restrict'],
                    'SDG2.C': ['target 2.c', 'target 2.8', 'food price', u'food price', u'food commod market'],
                    'SDG2.A': ['target 2.a', 'target 2.6', u'agricultur orient index', u'agricultur product capac', u'rural infrastructur', u'agricultur research']
                    },
            'SDG3': {
                    'SDG3.3': ['target 3.3', u'epidem', u'aid', 'hiv', u'tuberculosi', 'malaria', u'hepat b', u'tropic diseas'],
                    'SDG3.2': ['target 3.2', u'five mortal rate', u'neonat mortal rate', u'prevent death', u'1,000 live birth'],
                    'SDG3.1': ['target 3.1', u'matern mortal ratio', u'100,000 live birth'],
                    'SDG3.7': ['target 3.7', u'health care servic', u'healthcar servic', u'health care servic', u'famili plan', u'reproduct health',
                               u'adolesc birth rate'],
                    'SDG3.6': ['target 3.6', 'road traffic'],
                    'SDG3.5': ['target 3.5', u'substanc abus', u'narcot drug abus', 'alcohol', u'treatment intervent'],
                    'SDG3.4': ['target 3.4', u'non communic diseas', u'suicid mortal', 'mental health', u'prematur mortal'],
                    'SDG3.9': ['target 3.9', u'hazard chemic', u'air pollut', u'contamin', 'water', u'sanit', u'hygien', u'wash servic', u'poison'],
                    'SDG3.8': ['target 3.8', u'health coverag', u'financi risk protect', u'tracer intervent', u'health insur', u'health servic',
                               'child health', u'vaccin', u'vaccin'],
                    'SDG3.C': ['target 3.c', 'target 3.12', 'health worker', u'health financ', u'health workforc'],
                    'SDG3.B': ['target 3.b', 'target 3.11', u'medic research', u'health facil', 'public health'],
                    'SDG3.A': ['target 3.a', 'target 3.10', u'world health organ framework convent', 'tobacco'],
                    'SDG3.D': ['target 3.d', 'target 3.13', u'intern health regul', 'ihr', u'health emerg prepared', u'health risk']
                    },
            'SDG4': {
                    'SDG4.A': ['target 4.a', 'target 4.8', u'educ facil', u'school access', u'pedagog purpos', u'student disabl'],
                    'SDG4.B': ['target 4.b', 'target 4.9', 'scholarship', u'scholarship', u'higher educ'],
                    'SDG4.C': ['target 4.c', 'target 4.10', u'teacher', u'teacher train', u'pedagog train'],
                    'SDG4.1': ['target 4.1', u'free educ', u'equit educ', u'qualiti educ', u'primari educ', u'secondari educ', u'learn outcom',
                               u'profici level', u'young peopl'],
                    'SDG4.2': ['target 4.2', u'earli childhood develop', u'pre primari educ', u'organ learn', u'primari educ'],
                    'SDG4.3': ['target 4.3', u'technic educ', u'vocat educ', u'tertiari educ', u'univers'],
                    'SDG4.4': ['target 4.4', u'skill employ', u'inform commun technolog skill', u'ict skill', u'vocat skill'],
                    'SDG4.5': ['target 4.5', u'gender dispar', u'vocat train', u'pariti indic'],
                    'SDG4.6': ['target 4.6', u'literaci', u'numeraci'],
                    'SDG4.7': ['target 4.7', 'global citizenship', u'educ sustain develop', u'sustain develop educ', u'nation educ polici',
                               'curricula', u'teacher educ', u'student assess']
                    },
            'SDG5': {
                    'SDG5.A': ['target 5.a', 'target 5.7', u'right', 'land'],
                    'SDG5.C': ['target 5.c', 'target 5.9', u'public alloc', u'gender equal', u'empower'],
                    'SDG5.B': ['target 5.b', 'target 5.8', u'enabl technolog', 'phone'],
                    'SDG5.5': ['target 5.5', u'equal opportun leadership', u'parliament', 'parliament', u'local govern', u'manageri posit'],
                    'SDG5.4': ['target 5.4', 'unpaid care', u'domest work', u'share respons within household', u'unpaid domest', 'care work'],
                    'SDG5.6': ['target 5.6', 'sexual health', u'reproduct health', u'reproduct right', u'programm action intern confer popul develop',
                            u'beij platform action', u'decis regard sexual relat', u'contracept use', u'sexual relat'],
                    'SDG5.1': ['target 5.1', u'discrimin'],
                    'SDG5.3': ['target 5.3', u'marriag', u'femal genit', u'harm practic', u'marri'],
                    'SDG5.2': ['target 5.2', u'violenc', u'traffick', u'sexual exploit']
                    },
            'SDG6': {
                    'SDG6.2': ['target 6.2', u'sanit', u'hygien', u'open defec', u'hand wash', 'soap'],
                    'SDG6.3': ['target 6.3', u'water qualiti', u'pollut', u'dump', u'releas hazard', u'wastewat', u'recycl', u'reus'],
                    'SDG6.1': ['target 6.1', u'drink water'],
                    'SDG6.6': ['target 6.6', u'water relat ecosystem'],
                    'SDG6.4': ['target 6.4', u'freshwat', u'water scarciti', u'water use effici', u'water stress'],
                    'SDG6.5': ['target 6.5', u'water resourc manag', u'transboundari', u'water cooper'],
                    'SDG6.B': ['target 6.b', 'target 6.8', u'local commun', u'sanit manag'],
                    'SDG6.A': ['target 6.a', 'target 6.7', u'intern cooper', u'water harvest', u'desalin', u'water effici', u'wastewat treatment', u'technolog']
                    },
            'SDG7': {
                    'SDG7.1': ['target 7.1', u'energi servic', u'electr', u'clean fuel', u'clean technolog', u'afford'],
                    'SDG7.3': ['target 7.3', u'energi effici', u'energi intens', u'primari energi'],
                    'SDG7.2': ['target 7.2', u'renew energi', u'energi consumpt'],
                    'SDG7.A': ['target 7.a', 'target 7.4', u'intern cooper', u'clean energi research', u'technolog', u'infrastructur'],
                    'SDG7.B': ['target 7.b', 'target 7.5', u'energi servic', u'invest', u'energi effici', u'sustain energi']
                    },
            'SDG8': {
                    'SDG8.A': ['target 8.a', 'target 8.11', 'aid trade', u'least develop countri'],
                    'SDG8.B': ['target 8.b', 'target 8.12', u'youth employ', u'global job pact intern labour organ', u'intern labor organ',
                               u'employ programm', u'employ program'],
                    'SDG8.10': ['target 8.10', u'domest financi institut', u'bank servic', u'insur servic', u'financi servic', u'commerci bank branch', u'atm'],
                    'SDG8.4': ['target 8.4', u'global resourc effici', u'materi footprint'],
                    'SDG8.5': ['target 8.5', u'product employ', u'full employ', 'decent work', 'equal pay', u'hourli earn', u'unemploy rate'],
                    'SDG8.6': ['target 8.6', 'youth'],
                    'SDG8.7': ['target 8.7', u'forc labour', u'forc labor', u'modern slaveri', u'human traffick', 'child'],
                    'SDG8.1': ['target 8.1', u'econom growth', 'growth rate gdp per capita', 'product growth'],
                    'SDG8.2': ['target 8.2', u'econom product', u'econom diversif', u'technolog upgrad', u'innov', u'growth rate gdp per employ'],
                    'SDG8.3': ['target 8.3', u'develop orient polici', u'product activ', 'job creation', 'entrepreneurship', u'innov', u'inform employ'],
                    'SDG8.8': ['target 8.8', u'labour right', u'labor right', u'work environ', u'migrant worker', u'precari employ', u'occup injuri',
                               u'freedom associ collect bargain'],
                    'SDG8.9': ['target 8.9', u'local cultur', u'local product', 'tourism']
                    },
            'SDG9': {
                    'SDG9.1': ['target 9.1', u'infrastructur', u'equit access', 'season road', u'freight volum', u'passeng volum', u'econom develop'],
                    'SDG9.3': ['target 9.3', 'small scale'],
                    'SDG9.2': ['target 9.2', u'sustain industri', u'share employ', u'gross domest product', u'manufactur'],
                    'SDG9.5': ['target 9.5', u'research develop', u'scientif research', u'innov', 'public research', u'privat research', u'technolog capabl'],
                    'SDG9.4': ['target 9.4', u'resourc use effici', u'industri process', u'co2 emiss'],
                    'SDG9.A': ['target 9.a', 'target 9.6', u'infrastructur develop', u'support infrastructur'],
                    'SDG9.C': ['target 9.c', 'target 9.8', u'inform commun technolog', 'ict', 'internet', u'mobil network'],
                    'SDG9.B': ['target 9.b', 'target 9.7', u'domest', u'industri diversif', u'high tech industri', u'technolog develop']
                    },
            'SDG10': {
                    'SDG10.B': ['target 10.b', u'foreign direct invest', u'financi flow'],
                    'SDG10.C': ['target 10.c', u'migrant remitt', u'remitt corridor', u'remitt cost'],
                    'SDG10.A': ['target 10.a', u'differenti treatment', 'tariff'],
                    'SDG10.2': ['target 10.2', u'inclus', u'polit inclus'],
                    'SDG10.3': ['target 10.3', u'equal opportun', u'inequ', u'discriminatori'],
                    'SDG10.1': ['target 10.1', u'incom growth', u'household expenditur', u'incom per capita'],
                    'SDG10.6': ['target 10.6', u'econom institut', u'intern financi institut', u'vote right'],
                    'SDG10.7': ['target 10.7', u'migrat', u'mobil peopl', u'migrat polici', u'recruit cost'],
                    'SDG10.4': ['target 10.4', u'social protect', 'fiscal', 'wage', 'labour share', 'labor share'],
                    'SDG10.5': ['target 10.5', u'global financi market', u'financi institut', u'financi sound indic']
                    },
            'SDG11': {
                    'SDG11.C': ['target 11.c', u'sustain build', u'resili build', u'resourc effici build'],
                    'SDG11.B': ['target 11.b', 'human settlement', u'inclus', u'resourc effici', u'resili disast', 'sendai framework',
                                u'disast risk reduct', u'disast risk manag'],
                    'SDG11.A': ['target 11.a', u'econom link', 'social link', u'environment link', 'per urban', 'rural area', u'develop plan',
                                u'develop plan', u'develop plan'],
                    'SDG11.7': ['target 11.7', 'built up area', 'open space', 'public space', 'green space', u'harass', 'safe space', u'inclus space'],
                    'SDG11.6': ['target 11.6', u'environment impact', u'air qualiti', u'wast manag', u'urban solid wast', u'fine particul matter',
                                'pm2.5', 'PM 2.5', 'pm10', 'PM 10'],
                    'SDG11.5': ['target 11.5', u'disast'],
                    'SDG11.4': ['target 11.4', u'heritag'],
                    'SDG11.3': ['target 11.3', u'urban', 'human settlement', u'land consumpt rate', u'popul growth rate', u'civil societi',
                                u'urban plan', u'urban manag', u'direct particip'],
                    'SDG11.2': ['target 11.2', 'transport system', u'road safeti', 'public transport', u'sustain transport'],
                    'SDG11.1': ['target 11.1', u'hous', u'slum', u'urban popul', u'inform settlement', u'inadequ hous', u'afford hous']
                    },
            'SDG12': {
                    'SDG12.1': ['target 12.1', u'sustain consumpt', u'sustain product', '10 year framework', u'sustain consumpt product', 'scp'],
                    'SDG12.2': ['target 12.2', u'sustain manag', u'materi footprint', u'effici use'],
                    'SDG12.3': ['target 12.3', u'global food wast', u'food loss', u'post harvest loss'],
                    'SDG12.4': ['target 12.4', u'environment agreement', u'environment agreement', u'hazard wast'],
                    'SDG12.5': ['target 12.5', u'wast gener', u'recycl', u'recycl'],
                    'SDG12.6': ['target 12.6', u'compani', u'sustain report', u'sustain practic'],
                    'SDG12.7': ['target 12.7', u'public procur'],
                    'SDG12.8': ['target 12.8', u'natur', u'awar sustain develop', u'climat chang educ'],
                    'SDG12.A': ['target 12.a', 'target 12.9', u'sustain pattern', u'scientif capac', u'technolog capac', u'environment sound technolog'],
                    'SDG12.B': ['target 12.b', 'target 12.10', u'sustain develop impact', u'sustain tourism', u'monitor tool', u'evalu tool'],
                    'SDG12.C': ['target 12.c', 'target 12.11', 'fossil fuel', u'wast consumpt', u'market distort', u'taxat', u'harm subsidi']
                    },
            'SDG13': {
                    'SDG13.1': ['target 13.1', u'natur disast', u'hazard', u'adapt capac'],
                    'SDG13.2': ['target 13.2', u'climat chang measur', u'climat resili', u'greenhous ga emiss'],
                    'SDG13.A': ['target 13.4', 'target 13.a', u'unit nation framework convent climat chang', u'green climat fund', u'transpar'],
                    'SDG13.3': ['target 13.3', u'climat chang mitig', u'climat chang adapt', u'climat chang impact reduct', u'climat chang earli warn',
                                u'technolog transfer'],
                    'SDG13.B': ['target 13.5', 'target 13.b', u'climat chang plan', u'climat chang manag']
                    },
            'SDG14': {
                    'SDG14.B': ['target 14.b', 'target 14.9', 'fisher', u'marin market', 'small scale', u'fisheri', u'fisheri'],
                    'SDG14.C': ['target 14.c', 'target 14.10', u'unclo', 'use ocean', 'use ocean', u'futur we want', u'ocean resourc'],
                    'SDG14.A': ['target 14.a', 'target 14.8', u'marin technolog', u'intergovernment oceanograph commiss criteria guidelin',
                                'ocean health', u'marin biodivers'],
                    'SDG14.6': ['target 14.6', u'fisheri subsidi'],
                    'SDG14.7': ['target 14.7', u'marin resourc', u'aquacultur', 'tourism', u'sustain fisheri'],
                    'SDG14.4': ['target 14.4', u'regul harvest', u'overfish', u'fish', 'fish stock'],
                    'SDG14.5': ['target 14.5', u'conserv', u'coastal area', u'marin area', u'protect area'],
                    'SDG14.2': ['target 14.2', u'marin ecosystem', u'coastal ecosystem', u'healthi ocean', u'product ocean', u'nation exclus econom zone'],
                    'SDG14.3': ['target 14.3', u'ocean acidif', u'marin acid'],
                    'SDG14.1': ['target 14.1', u'marin pollut', u'debri', u'nutrient pollut', u'coastal eutroph']
                    },
            'SDG15':{
                    'SDG15.C': ['target 15.c', 'target 15.12', u'sustain livelihood opportun', u'poach', u'traffick'],
                    'SDG15.B': ['target 15.b', 'target 15.11', u'sustain forest manag'],
                    'SDG15.A': ['target 15.a', 'target 15.10', u'use biodivers', u'biodivers use', 'use ecosystem', u'ecosystem use'],
                    'SDG15.3': ['target 15.3', u'desertif', 'drought', 'flood', u'degrad neutral', u'degrad land'],
                    'SDG15.2': ['target 15.2', u'deforest', u'restor degrad forest', u'afforest', u'reforest', u'sustain forest manag'],
                    'SDG15.1': ['target 15.1', u'freshwat', 'forest', 'wetland', 'mountain', 'dryland'],
                    'SDG15.7': ['target 15.7', u'poach', u'protect speci', 'flora', 'fauna', u'wildlif'],
                    'SDG15.6': ['target 15.6', u'genet resourc'],
                    'SDG15.5': ['target 15.5', u'natur habitat', u'loss biodivers', u'biodivers loss', u'extinct', u'threaten speci', 'red list index'],
                    'SDG15.4': ['target 15.4', 'mountain'],
                    'SDG15.9': ['target 15.9', u'ecosystem valu', u'biodivers valu', u'aichi biodivers target', u'strateg plan biodivers',
                                u'aichi biodivers target'],
                    'SDG15.8': ['target 15.8', u'invas alien speci', u'prioriti speci']
                    },
            'SDG16': {
                    'SDG16.4': ['target 16.4', u'illicit financi flow', u'arm flow', u'stolen asset', u'organ crime', u'organ crime'],
                    'SDG16.5': ['target 16.5', u'corrupt', u'briberi', u'busi'],
                    'SDG16.6': ['target 16.6', u'effect', u'account institut', u'transpar institut'],
                    'SDG16.7': ['target 16.7', u'decis make'],
                    'SDG16.1': ['target 16.1', u'reduc violenc', 'conflict', u'death'],
                    'SDG16.2': ['target 16.2', u'abus', u'exploit', u'traffick', 'children', u'psycholog', u'physic punish'],
                    'SDG16.3': ['target 16.3', u'equal access justic', 'rule law', u'victim', u'unsentenc'],
                    'SDG16.8': ['target 16.8', u'global govern', u'develop countri'],
                    'SDG16.9': ['target 16.9', u'legal ident', u'birth registr'],
                    'SDG16.A': ['target 16.a', 'target 16.11', u'violenc', u'terrorismcrim', u'crime'],
                    'SDG16.B': ['target 16.b', 'target 16.12', u'non discriminatori law', u'non discriminatori polici'],
                    'SDG16.10': ['target 16.10', u'access inform', u'fundament freedom']
                    },
            'SDG17': {
                    'SDG17.1': ['target 17.1', u'resourc mobil', u'domest capac', 'tax', u'revenu collect'],
                    'SDG17.3': ['target 17.3', u'financi resourc'],
                    'SDG17.2': ['target 17.2', u'develop assist commit', 'oda', 'oecd'],
                    'SDG17.5': ['target 17.5', u'promot'],
                    'SDG17.4': ['target 17.4', u'debt sustain', u'debt financ', 'debt relief', u'debt restructur', u'reduc debt', u'debt distress'],
                    'SDG17.7': ['target 17.7', u'environment sound technolog'],
                    'SDG17.6': ['target 17.6', u'scienc', u'technolog', u'innov', u'knowledg share', u'technolog cooper agreement'],
                    'SDG17.9': ['target 17.9', u'capac build', u'nation plan'],
                    'SDG17.8': ['target 17.8', u'technolog bank', u'innov capac'],
                    'SDG17.17': ['target 17.17', 'data', u'monitor', u'account'],
                    'SDG17.16': ['target 17.16', u'global partnership', u'multi stakehold partnership'],
                    'SDG17.11': ['target 17.11', u'export'],
                    'SDG17.10': ['target 17.10', u'multilater trade system', u'doha develop agenda'],
                    'SDG17.13': ['target 17.13', u'macroeconom stabil', u'polici coordin', u'polici coher'],
                    'SDG17.12': ['target 17.12', u'duti free', 'quota free', u'market access'],
                    'SDG17.15': ['target 17.15', u'multi stakehold partnership'],
                    'SDG17.14': ['target 17.14', u'polici coher'],
                    'SDG17.19': ['target 17.19', u'exist initi', u'gross domest product', u'statist capac build', u'birth registr', u'death registr'],
                    'SDG17.18': ['target 17.18', u'capac build', u'small island develop state', u'disaggreg', u'reliabl data', u'disaggreg']
                    }
        }
